################### env.profile local (h2 memory db) start ##########################
---
spring:
  profiles: local
  #H2 console setting
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
      enabled: true

  # datasource Configuration
  datasource:
    driverClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:exchange;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: local
    password: 

#log level
logging:
  level:
    org.springframework.web: DEBUG
################### env.profile local (h2 memory db) end ##########################